#Bol database
spring.config.import=optional:classpath:external-config-bol.properties
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${DB_URL_BOL}
spring.datasource.username=${DB_USR_BOL}
spring.datasource.password=${DB_PWD_BOL}
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.connection-timeout=20000
#Encryption variables
encryption.algorithm=${ALGO_ENCRYPT_BOL}
encryption.iteration-count=${ENCRYPT_ITERATION_BOL}
encryption.salt-length=${ENCRYPT_SALT_LENGTH_BOL}
decryption.passphrase=${DECRYPT_PASS_BOL}