#Col database configuration (Postgres)
spring.config.import=optional:classpath:external-config-col.properties
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL_COL}
spring.datasource.username=${DB_USR_COL}
spring.datasource.password=${DB_PWD_COL}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.connection-timeout=20000
#Encryption variables
encryption.algorithm=${ALGO_ENCRYPT_COL}
encryption.iteration-count=${ENCRYPT_ITERATION_COL}
encryption.salt-length=${ENCRYPT_SALT_LENGTH_COL}
decryption.passphrase=${DECRYPT_PASS_COL}
